export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h2>Root Header</h2>
        {children}
        <h2>Root Footer</h2>
        </body>
    </html>
  )
}
