export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function DashboardLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>
        <h2>Header</h2>
            {children}
            
            <h2>Footer</h2>
            </body>
        
      </html>
    )
  }
  